 services:
  marzban:
    image: gozargah/marzban:dev
    restart: on-failure
    env_file: env

    environment:
      UVICORN_UDS: "/run/marzban.socket"
      SQLALCHEMY_DATABASE_URL: "sqlite:////var/lib/marzban/db.sqlite3"
      XRAY_JSON: "/xray_config.json"
      XRAY_FALLBACK_INBOUND_TAG: "TROJAN_FALLBACK_INBOUND"

    volumes:
      - /var/lib/marzban/run:/run
      - ./xray_config.json:/xray_config.json
      - /var/lib/marzban:/var/lib/marzban
      - /etc/letsencrypt/:/etc/letsencrypt

    ports:
      - "443:443"

  nginx:
    image: nginx
    volumes:
      - /var/lib/marzban/run:/run
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
